var outdoorDict={
  "Alfiero Center":["Baldy Hall","Lockwood Library","O’Brian Hall","Park Hall","Jacobs Management Center","Clemens Hall","Baird Hall","Talbert Hall","Hochstetter Hall","Cooke Hall","Natural Sciences Complex"],
  "Alumni Arena":["Slee Hall","Center for the Arts","Bissell Hall","Child Care Center"],
  "Baird Hall":["Center for the Arts","Alfiero Center","Slee Hall","Clemens Hall","Lockwood Library","Jacobs Management Center"],
  "Baldy Hall":["O’Brian Hall","Lockwood Library","Student Union","Alfiero Center","Park Hall","Capen Hall","Bell Hall","Commons","Clemens Hall"],
  "Bell Hall":["Baldy Hall","Furnas Hall","Student Union","Knox Lecture Hall","Bonner Hall","Commons"],
  "Bissell Hall":["Alumni Arena"],
  "Bonner Hall":["Knox Lecture Hall","Ketter Hall","Norton Hall","Bell Hall","Capen Hall","Furnas Hall"],
  "Bookstore":[ "Commons"],
  "Capen Hall":["Hochstetter Hall","Cooke Hall","Natural Sciences Complex","Fronczak Hall","Bonner Hall","Baldy Hall","Norton Hall","Talbert Hall","O’Brian Hall"],
  "Center for the Arts":["Baird Hall","Alumni Arena","Slee Hall","Commons"],
  "Child Care Center":["Alumni Arena"],
  "Clemens Hall":["Baldy Hall","Alfiero Center","Lockwood Library","Baird Hall","Student Union","Commons","Jacobs Management Center"],
  "Commons":["Clemens Hall","Bell Hall","Baldy Hall","Student Union","Center for the Arts","Bookstore","Furnas Hall"],
  "Cooke Hall":["Talbert Hall","Capen Hall","Alfiero Center","Hochstetter Hall","Natural Sciences Complex"],
  "Davis Hall":["Furnas Hall","Ketter Hall","Jarvis Hall"],
  "Fronczak Hall":["Mathematics Building","Natural Sciences Complex","Talbert Hall","Capen Hall"],
  "Hochstetter Hall":["Capen Hall","Alfiero Center","Cooke Hall","Talbert Hall","Natural Sciences Complex"],
  "Jacobs Management Center":["Baird Hall","Alfiero Center","Park Hall","Lockwood Library","Clemens Hall"],
  "Jarvis Hall":["Davis Hall","Ketter Hall","Furnas Hall"],
  "Ketter Hall":["Bonner Hall","Davis Hall","Jarvis Hall","Furnas Hall"],
  "Knox Lecture Hall":["Bonner Hall","Norton Hall","O’Brian Hall","Bell Hall"],
  "Lockwood Library":["Baird Hall","Alfiero Center","Baldy Hall","Clemens Hall","Jacobs Management Center","Student Union"],
  "Mathematics Building":["Fronczak Hall"],
  "Natural Sciences Complex":["Alfiero Center","Capen Hall","Cooke Hall","Fronczak Hall","Hochstetter Hall","Talbert Hall"],
  "Norton Hall":["Bonner Hall","Capen Hall","Knox Lecture Hall","O’Brian Hall"],
  "O’Brian Hall":["Capen Hall","Alfiero Center","Baldy Hall","Knox Lecture Hall","Norton Hall","Park Hall"],
  "Park Hall":["Baldy Hall","Alfiero Center","Jacobs Management Center","O’Brian Hall"],
  "Slee Hall":["Alumni Arena","Baird Hall","Center for the Arts"],
  "Student Union":["Lockwood Library","Baldy Hall","Bell Hall","Clemens Hall","Commons"],
  "Talbert Hall":["Cooke Hall","Alfiero Center","Capen Hall","Fronczak Hall","Hochstetter Hall","Natural Sciences Complex"],
  "Furnas Hall":["Davis Hall","Bonner Hall","Bell Hall","Commons","Jarvis Hall","Ketter Hall"],
};

