var shortestDict={
  "Tim Hortons":["Alfiero Center","Baldy Hall","Lockwood Library","Jacobs Management Center","Baird Hall","Center for the Arts","Alumni Arena"],
  "Alfiero Center":["Park Hall","Jacobs Management Center","O’Brian Hall","Tim Hortons"],
  "Alumni Arena":["Center for the Arts","Tim Hortons","Slee Hall" ,"Baird Hall","Child Care Center"],
  "Baird Hall":["Slee Hall","Clemens Hall","Tim Hortons","Alumni Arena"],
  "Baldy Hall":["Tim Hortons","Capen Hall","Bell Hall","Lockwood Library","Student Union","O’Brian Hall","Knox Lecture Hall","Alfiero Center","Park Hall"],
  "Bell Hall":["Knox Lecture Hall","Commons","Bookstore","Baldy Hall","Ketter Hall","Furnas Hall","Student Union","Bonner Hall"],
  "Bissell Hall":["Alumni Arena"],
  "Bonner Hall":["Ketter Hall","Norton Hall","Bell Hall","Knox Lecture Hall","Furnas Hall"],
  "Bookstore":[ "Commons"],
  "Capen Hall":["Norton Hall","Baldy Hall","Talbert Hall"],
  "Center for the Arts":["Alumni Arena","Slee Hall","Commons"],
  "Child Care Center":["Alumni Arena"],
  "Clemens Hall":["Lockwood Library","Baird Hall","Student Union"],
  "Commons":["Student Union","Center for the Arts","Bookstore","Furnas Hall"],
  "Cooke Hall":["Hochstetter Hall","Natural Sciences Complex"],
  "Davis Hall":["Ketter Hall","Jarvis Hall"],
  "Fronczak Hall":["Natural Sciences Complex","Talbert Hall","Capen Hall"],
  "Hochstetter Hall":["Cooke Hall","Talbert Hall","Natural Sciences Complex"],
  "Jacobs Management Center":["Alfiero Center","Park Hall"],
  "Jarvis Hall":["Davis Hall","Ketter Hall","Furnas Hall"],
  "Ketter Hall":["Bonner Hall","Davis Hall","Jarvis Hall","Furnas Hall"],
  "Knox Lecture Hall":["Bonner Hall","Norton Hall","O’Brian Hall","Baldy Hall","Bell Hall"],
  "Lockwood Library":["Alfiero Center","Baldy Hall","Clemens Hall","Jacobs Management Center","Student Union"],
  "Mathematics Building":["Natural Sciences Complex"],
  "Natural Sciences Complex":["Mathematics Building","Cooke Hall","Fronczak Hall","Hochstetter Hall","Talbert Hall"],
  "Norton Hall":["Bonner Hall","Capen Hall","Knox Lecture Hall","O’Brian Hall"],
  "O’Brian Hall":["Baldy Hall","Knox Lecture Hall","Norton Hall","Park Hall"],
  "Park Hall":["Alfiero Center","Jacobs Management Center","O’Brian Hall"],
  "Slee Hall":["Baird Hall","Center for the Arts"],
  "Student Union":["Baldy Hall","Bell Hall","Clemens Hall","Commons"],
  "Talbert Hall":["Capen Hall","Fronczak Hall","Hochstetter Hall","Natural Sciences Complex"],
  "Furnas Hall":["Bell Hall","Commons","Jarvis Hall","Ketter Hall"],
};
