var shortestDict={
  "Tim Hortons":["Alfiero Center","Baldy Hall","Lockwood Library","Jacobs Management Center","Baird Hall","Center for the Arts","Alumni Arena","Park Hall"],
  "Alfiero Center":["Park Hall","Jacobs Management Center","O’Brian Hall","Tim Hortons"],
  "Alumni Arena":["Bissell Hall","Center for the Arts","Tim Hortons","Slee Hall" ,"Baird Hall","Child Care Center"],
  "Baird Hall":["Baldy Hall","Slee Hall","Clemens Hall","Tim Hortons","Alumni Arena"],
  "Baldy Hall":["Baird Hall","Tim Hortons","Capen Hall","Bell Hall","Lockwood Library","Student Union","O’Brian Hall","Knox Lecture Hall"],
  "Bell Hall":["Knox Lecture Hall","Commons","Bookstore","Baldy Hall","Ketter Hall","Furnas Hall","Student Union","Bonner Hall"],
  "Bissell Hall":["Alumni Arena"],
  "Bonner Hall":["Capen Hall","Davis Hall","Fronczak Hall","Ketter Hall","Norton Hall","Bell Hall","Knox Lecture Hall","Furnas Hall"],
  "Bookstore":[ "Student Union","Furnas Hall","Commons","Bell Hall","Davis Hall"],
  "Capen Hall":["Talbert Hall","Hochstetter Hall","Fronczak Hall","Bonner Hall","Norton Hall","Baldy Hall","O’Brian Hall","Ketter Hall"],
  "Center for the Arts":["Child Care Center","Tim Hortons","Commons","Alumni Arena","Slee Hall"],
  "Child Care Center":["Alumni Arena","Center for the Arts"],
  "Clemens Hall":["Slee Hall","Lockwood Library","Baird Hall","Student Union","Commons"],
  "Commons":["Student Union","Bell Hall","Clemens Hall","Center for the Arts","Bookstore","Furnas Hall"],
  "Cooke Hall":["Hochstetter Hall","Natural Sciences Complex"],
  "Davis Hall":["Bonner Hall","Ketter Hall","Jarvis Hall","Bookstore"],
  "Fronczak Hall":["Bonner Hall","Natural Sciences Complex","Talbert Hall","Capen Hall","Mathematics Building"],
  "Furnas Hall":["Bonner Hall","Bookstore","Knox Lecture Hall","Bell Hall","Commons","Jarvis Hall","Ketter Hall"],
  "Hochstetter Hall":["O’Brian Hall","Cooke Hall","Talbert Hall","Natural Sciences Complex","Capen Hall"],
  "Jacobs Management Center":["Alfiero Center","Park Hall","Tim Hortons"],
  "Jarvis Hall":["Davis Hall","Ketter Hall","Furnas Hall"],
  "Ketter Hall":["Bell Hall","Capen Hall","Bonner Hall","Davis Hall","Jarvis Hall","Furnas Hall"],
  "Knox Lecture Hall":["Furnas Hall","Bonner Hall","Norton Hall","O’Brian Hall","Baldy Hall","Bell Hall","Student Union"],
  "Lockwood Library":["Tim Hortons","Baldy Hall","Clemens Hall","Student Union"],
  "Mathematics Building":["Natural Sciences Complex","Fronczak Hall"],
  "Natural Sciences Complex":["Mathematics Building","Cooke Hall","Fronczak Hall","Hochstetter Hall","Talbert Hall"],
  "Norton Hall":["Bonner Hall","Capen Hall","Knox Lecture Hall","O’Brian Hall"],
  "O’Brian Hall":["Alfiero Center","Hochstetter Hall","Capen Hall","Baldy Hall","Knox Lecture Hall","Norton Hall","Park Hall"],
  "Park Hall":["Alfiero Center","Jacobs Management Center","O’Brian Hall","Tim Hortons"],
  "Slee Hall":["Clemens Hall","Baird Hall","Center for the Arts","Alumni Arena"],
  "Student Union":["Bookstore","Lockwood Library","Knox Lecture Hall","Baldy Hall","Bell Hall","Clemens Hall","Commons"],
  "Talbert Hall":["Capen Hall","Fronczak Hall","Hochstetter Hall","Natural Sciences Complex"]
};
