var dict={
  "Alfiero Center":{},
  "Alumni Arena":{},
  "Baird Hall":{},
  "Baldy Hall":{},
  "Bell Hall":{},
  "Bissell Hall":{},
  "Bonner Hall":{},
  "Bookstore":{},
  "Capen Hall":{},
  "Center for the Arts":{},
  "Child Care Center":{},
  "Clemens Hall":{},
  "Commons":{},
  "Cooke Hall":{},
  "Davis Hall":{},
  "Fronczak Hall":{},
  "Hochstetter Hall":{},
  "Jacobs Management Center":{},
  "Jarvis Hall":{},
  "Ketter Hall":{},
  "Knox Lecture Hall":{},
  "Lockwood Library":{},
  "Mathematics Building":{},
  "Natural Sciences Complex":{},
  "Norton Hall":{},
  "O’Brian Hall":{},
  "Park Hall":{},
  "Slee Hall":{},
  "Student Union":{},
  "Talbert Hall":{},
};

for(var key in dict){
  alert(key);
}
